# Generated by Django 5.2.3 on 2025-06-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_profitlossreport_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitlossreport',
            name='inventory',
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
            preserve_default=False,
        ),
    ]
