# Generated by Django 5.2.3 on 2025-06-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_owner_customuser_admin_owner_item_owner_and_more'),
        ('inventory', '0003_remove_profitlossreport_inventory_and_more'),
    ]

    operations = [
    ]
